/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realisering15;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * @author Grupp15
 */
public class AgentFonster extends javax.swing.JFrame {

    private static InfDB databas;
    private String id;

    /**
     * Creates new form AgentFonster
     */
    public AgentFonster(InfDB databas, String id) {
        this.id = id;
        this.databas = databas;
        initComponents();
        fyllCbValjMetod();
        btnTillbakaTillAdmin.setVisible(false);
        gorBtnTillbakaTillAdminSynlig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lblValkommenAgent = new javax.swing.JLabel();
        cblistaMetoderAgent = new javax.swing.JComboBox<>();
        btnOkAgent = new javax.swing.JButton();
        btnLoggaUtAgent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTillbakaTillAdmin = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValkommenAgent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValkommenAgent.setText("Hej Agent!");

        cblistaMetoderAgent.setSelectedItem(cblistaMetoderAgent);

        btnOkAgent.setText("OK");
        btnOkAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkAgentActionPerformed(evt);
            }
        });

        btnLoggaUtAgent.setText("Logga ut");
        btnLoggaUtAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtAgentActionPerformed(evt);
            }
        });

        jLabel1.setText("Välj en åtgärd");

        btnTillbakaTillAdmin.setText("Tillbaka till adminfönster");
        btnTillbakaTillAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoggaUtAgent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbakaTillAdmin)
                        .addGap(54, 54, 54)
                        .addComponent(btnOkAgent)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblValkommenAgent)
                        .addGap(181, 181, 181))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cblistaMetoderAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValkommenAgent)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cblistaMetoderAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoggaUtAgent)
                    .addComponent(btnOkAgent)
                    .addComponent(btnTillbakaTillAdmin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metod som fyller comboBoxen med olika val en agent kan göra
     */
    private void fyllCbValjMetod() {
        ArrayList<String> metoder = new ArrayList<String>();
        metoder.add("Ändra lösenord");
        metoder.add("Registrera alien");
        metoder.add("Ändra aliens information");
        metoder.add("Lista alla aliens för en plats");
        metoder.add("Lista alla aliens av en ras");
        metoder.add("Lista över aliens registrerade mellan två datum");
        metoder.add("Registrera ny utrustning");
        metoder.add("Visa info om en alien");
        metoder.add("Visa områdeschef över utvalt område");
        for (String enMetod : metoder) {
            cblistaMetoderAgent.addItem(enMetod);
        }
    }

    /**
     * Metod som fyller comboBoxen med olika val en agent kan göra
     */
    private void btnOkAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkAgentActionPerformed
        //Kontrollerar vilken åtgärd som valts
        String valdMetod = cblistaMetoderAgent.getSelectedItem().toString();
        if (valdMetod.equals("Ändra lösenord")) {
            new AgentNyttLosenord(databas, id).setVisible(true);
        }
        if (valdMetod.equals("Registrera alien")) {
            new AgentLaggTillAlien(databas, id).setVisible(true);
        }
        if (valdMetod.equals("Ändra aliens information")) {
            new AgentUppdateraAlien(databas, id).setVisible(true);
        }
        if (valdMetod.equals("Lista alla aliens för en plats")) {
            new AgentListaAlienPlats(databas, id).setVisible(true);
        }
        if (valdMetod.equals("Lista över aliens registrerade mellan två datum")) {
            new AgentListaAlienDatum(databas, id).setVisible(true);
        }
        if (valdMetod.equals("Registrera ny utrustning")) {
            new AgentLaggTillUtr(databas, id).setVisible(true);
        }
        if (valdMetod.equals("Visa info om en alien")) {
            new AgentVisaInfoAlien(databas, id).setVisible(true);
        }
        if (valdMetod.equals("Visa områdeschef över utvalt område")) {
            new AgentVisaOmrC(databas, id).setVisible(true);
        }
        if (valdMetod.equals("Lista alla aliens av en ras")) {
            new AgentListaAlienRas(databas, id).setVisible(true);
        }
    }//GEN-LAST:event_btnOkAgentActionPerformed

    /**
     * Metod som tar användaren tillbaka till startsidan
     */
    private void btnLoggaUtAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtAgentActionPerformed
        new Start(databas).setVisible(true);
        AgentFonster.this.dispose();
    }//GEN-LAST:event_btnLoggaUtAgentActionPerformed

    /**
     * Metod som tar användaren tillbaka till adminsidan
     */
    private void btnTillbakaTillAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillAdminActionPerformed
        AgentFonster.this.dispose();
    }//GEN-LAST:event_btnTillbakaTillAdminActionPerformed

    /**
     * Metod som tar gör btnTillbakaTillAdmin synlig om agenten är admin
     */
    public void gorBtnTillbakaTillAdminSynlig() {
        try {
            String adminStatus = databas.fetchSingle("SELECT Administrator FROM agent WHERE Agent_ID=" + id);
            
            if (adminStatus.equals("J")) {
                btnTillbakaTillAdmin.setVisible(true);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaUtAgent;
    private javax.swing.JButton btnOkAgent;
    private javax.swing.JButton btnTillbakaTillAdmin;
    private javax.swing.JComboBox<String> cblistaMetoderAgent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lblValkommenAgent;
    // End of variables declaration//GEN-END:variables

}
