 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realisering15;

import java.util.ArrayList;
import javax.swing.JComboBox;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;


/**
 *
 * @author ander
 */
public class AgentFonster extends javax.swing.JFrame {
    private static InfDB databas;
    private String id;
    private String[] allaMetoder;
    
    /**
     * Creates new form AgentFonster
     */
    public AgentFonster(InfDB databas, String id) {
        this.id=id;
        this.databas=databas;
        initComponents();
        fyllCbValjMetod();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lblValkommenAgent = new javax.swing.JLabel();
        cblistaMetoderAgent = new javax.swing.JComboBox<>();
        btnOkAgent = new javax.swing.JButton();
        btnLoggaUtAgent = new javax.swing.JButton();
        btnFul = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValkommenAgent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValkommenAgent.setText("Hej Agent!");

        cblistaMetoderAgent.setSelectedItem(cblistaMetoderAgent);
        cblistaMetoderAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblistaMetoderAgentActionPerformed(evt);
            }
        });

        btnOkAgent.setText("Ok!");
        btnOkAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkAgentActionPerformed(evt);
            }
        });

        btnLoggaUtAgent.setText("Logga ut");
        btnLoggaUtAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtAgentActionPerformed(evt);
            }
        });

        btnFul.setText("FulKnapp");
        btnFul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFulActionPerformed(evt);
            }
        });

        jLabel1.setText("Välj en metod");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLoggaUtAgent)
                                .addGap(100, 100, 100)
                                .addComponent(btnFul))
                            .addComponent(lblValkommenAgent))
                        .addGap(18, 18, 18)
                        .addComponent(btnOkAgent)
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cblistaMetoderAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValkommenAgent)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cblistaMetoderAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLoggaUtAgent)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFul)
                            .addComponent(btnOkAgent))
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fyllCbValjMetod()
    {
        ArrayList<String> metoder = new ArrayList<String>();
        metoder.add("Ändra lösenord");
        metoder.add("Registrera alien");
        metoder.add("Ändra aliens information");
        metoder.add("Lista alla aliens för en plats");
        metoder.add("Lista över aliens registrerade mellan två datum");
        metoder.add("Registrera ny utrustning");
        metoder.add("Visa info om en alien");
        metoder.add("Visa områdeschef över utvalt område");
        for(String enMetod : metoder)
        {
            cblistaMetoderAgent.addItem(enMetod);
        }
    }
    private void cblistaMetoderAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblistaMetoderAgentActionPerformed
        // Metoder en agent kan välja 
    }//GEN-LAST:event_cblistaMetoderAgentActionPerformed

    private void btnOkAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkAgentActionPerformed
    String valdMetod = cblistaMetoderAgent.getSelectedItem().toString();
    if(valdMetod.equals("Ändra lösenord"))
    {
        new AgentNyttLosenord(databas,id).setVisible(true);
    }
    if(valdMetod.equals("Registrera alien"))
    {
        new AgentLaggTillAlien(databas,id).setVisible(true);
    }
        
            
        
        
    }//GEN-LAST:event_btnOkAgentActionPerformed

    private void btnLoggaUtAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtAgentActionPerformed
        new Start().setVisible(true);
        AgentFonster.this.dispose();
    }//GEN-LAST:event_btnLoggaUtAgentActionPerformed

    private void btnFulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFulActionPerformed
        // TODO add your handling code here:
        new AgentVisaOmrC(databas, id).setVisible(true);
    }//GEN-LAST:event_btnFulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AgentFonster(databas).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFul;
    private javax.swing.JButton btnLoggaUtAgent;
    private javax.swing.JButton btnOkAgent;
    private javax.swing.JComboBox<String> cblistaMetoderAgent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lblValkommenAgent;
    // End of variables declaration//GEN-END:variables
   
}
