/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realisering15;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;

/**
 *
 * @author felixlundqvist
 */
public class AgentAndraRasPaAlien extends javax.swing.JFrame {

    private static InfDB databas;
    private String id;

    /**
     * Creates new form AgentAndraRasPaAlien
     */
    public AgentAndraRasPaAlien(InfDB databas, String id) {
        initComponents();
        this.databas = databas;
        this.id = id;
        fyllCbValjAlienID();
        fyllCbValjRas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAndraRas = new javax.swing.JLabel();
        cbValjAlienID = new javax.swing.JComboBox<>();
        cbValjRas = new javax.swing.JComboBox<>();
        lblAlienID = new javax.swing.JLabel();
        lblNyRas = new javax.swing.JLabel();
        txtAreaVisaRasInfo = new javax.swing.JScrollPane();
        txtAreaVisaRas = new javax.swing.JTextArea();
        txtRasAttribut = new javax.swing.JTextField();
        lblRasAttribut = new javax.swing.JLabel();
        btnBekrafta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAndraRas.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblAndraRas.setText("Ändra ras för en Alien");

        cbValjAlienID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjAlienIDActionPerformed(evt);
            }
        });

        lblAlienID.setText("Välj Alien ID:");

        lblNyRas.setText("Ny Ras:");

        txtAreaVisaRas.setEditable(false);
        txtAreaVisaRas.setColumns(20);
        txtAreaVisaRas.setRows(5);
        txtAreaVisaRasInfo.setViewportView(txtAreaVisaRas);

        lblRasAttribut.setText("Antal armar/boogies:");

        btnBekrafta.setText("Bekräfta");
        btnBekrafta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBekraftaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblAndraRas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlienID)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbValjAlienID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbValjRas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                .addComponent(txtRasAttribut, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBekrafta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblNyRas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRasAttribut)
                            .addComponent(txtAreaVisaRasInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAndraRas)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAreaVisaRasInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlienID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbValjAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNyRas)
                    .addComponent(lblRasAttribut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbValjRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRasAttribut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnBekrafta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fyllCbValjAlienID() {
        try {
            ArrayList<String> allaAlienID = databas.fetchColumn("SELECT alien_ID FROM Alien");

            Collections.sort(allaAlienID);

            for (String ettAlienID : allaAlienID) {
                cbValjAlienID.addItem(ettAlienID);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }

    private void fyllCbValjRas() {
        ArrayList<String> raser = new ArrayList<String>();
        raser.add("Boglodite");
        raser.add("Worm");
        raser.add("Squid");

        Collections.sort(raser);

        for (String enRas : raser) {
            cbValjRas.addItem(enRas);
        }
    }


    private void btnBekraftaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBekraftaActionPerformed


    }//GEN-LAST:event_btnBekraftaActionPerformed

    private void cbValjAlienIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjAlienIDActionPerformed
        txtAreaVisaRas.setText("");

        try {
            String valtID = cbValjAlienID.getSelectedItem().toString();

            ArrayList<String> bogloditer = databas.fetchColumn("SELECT alien_id FROM boglodite");
            ArrayList<String> worms = databas.fetchColumn("SELECT alien_id FROM worm");
            ArrayList<String> squids = databas.fetchColumn("SELECT alien_id FROM squid");

            String ras = "";
            String attribut = "";
            for (String enBoglodite : bogloditer) {
                if (enBoglodite.equals(valtID)) {
                    ras = "Boglodite";
                    attribut = databas.fetchSingle("SELECT antal_boogies FROM boglodite WHERE alien_id="+valtID);
                }
            }
            for (String enWorm : worms) {
                if (enWorm.equals(valtID)) {
                    ras = "Worm";
                }
            }
            for (String enSquid : squids) {
                if (enSquid.equals(valtID)) {
                    ras = "Squid";
                    attribut = databas.fetchSingle("SELECT antal_armar FROM squid WHERE alien_id="+valtID);
                }
            }
            txtAreaVisaRas.append(ras+"\t"+attribut);

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }//GEN-LAST:event_cbValjAlienIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBekrafta;
    private javax.swing.JComboBox<String> cbValjAlienID;
    private javax.swing.JComboBox<String> cbValjRas;
    private javax.swing.JLabel lblAlienID;
    private javax.swing.JLabel lblAndraRas;
    private javax.swing.JLabel lblNyRas;
    private javax.swing.JLabel lblRasAttribut;
    private javax.swing.JTextArea txtAreaVisaRas;
    private javax.swing.JScrollPane txtAreaVisaRasInfo;
    private javax.swing.JTextField txtRasAttribut;
    // End of variables declaration//GEN-END:variables
}
