/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realisering15;
import java.util.ArrayList;
import javax.swing.JComboBox;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/**
 *
 * @author felixlundqvist
 */
public class AgentAndraInfoOmAlien extends javax.swing.JFrame {
     private static InfDB databas;
    private String id;
    private String alienId;

    /**
     * Creates new form AgentAndraInfoOmAlien
     */
    public AgentAndraInfoOmAlien(InfDB databas,String id,String alienId) {
        this.id=id;
        this.databas=databas;
        this.alienId=alienId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAndraInfo = new javax.swing.JLabel();
        lblIDtForAlien = new javax.swing.JLabel();
        txtNyID = new javax.swing.JTextField();
        lblNamnForAlien = new javax.swing.JLabel();
        txtNyNamn = new javax.swing.JTextField();
        lblTelNrForAlien = new javax.swing.JLabel();
        txtNyTelNr = new javax.swing.JTextField();
        lblPlatsForAlien = new javax.swing.JLabel();
        txtNyPlats = new javax.swing.JTextField();
        lblAnsvarigAgent = new javax.swing.JLabel();
        txtNyAnsvarigAgent = new javax.swing.JTextField();
        lblRegDatum = new javax.swing.JLabel();
        txtNyttDatum = new javax.swing.JTextField();
        lblRas = new javax.swing.JLabel();
        txtNyRas = new javax.swing.JTextField();
        btnAndraUppgifter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAndraInfo.setText("Ändra information");

        lblIDtForAlien.setText("ID:");

        txtNyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNyIDActionPerformed(evt);
            }
        });

        lblNamnForAlien.setText("Namn:");

        txtNyNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNyNamnActionPerformed(evt);
            }
        });

        lblTelNrForAlien.setText("Telefon:");

        txtNyTelNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNyTelNrActionPerformed(evt);
            }
        });

        lblPlatsForAlien.setText("Plats:");

        txtNyPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNyPlatsActionPerformed(evt);
            }
        });

        lblAnsvarigAgent.setText("Ansvarig Agent:");

        txtNyAnsvarigAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNyAnsvarigAgentActionPerformed(evt);
            }
        });

        lblRegDatum.setText("Registreringsdatum:");

        txtNyttDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNyttDatumActionPerformed(evt);
            }
        });

        lblRas.setText("Ras:");

        txtNyRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNyRasActionPerformed(evt);
            }
        });

        btnAndraUppgifter.setText("Ändra");
        btnAndraUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraUppgifterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlatsForAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNyttDatum))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegDatum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNyAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAnsvarigAgent)
                                .addGap(18, 18, 18)
                                .addComponent(txtNyPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelNrForAlien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNyTelNr, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNamnForAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRas, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDtForAlien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNyID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(lblAndraInfo))
                                    .addComponent(txtNyNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNyRas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(btnAndraUppgifter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblAndraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDtForAlien)
                            .addComponent(txtNyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRas)
                    .addComponent(txtNyRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamnForAlien)
                    .addComponent(txtNyNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelNrForAlien)
                    .addComponent(txtNyTelNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsvarigAgent)
                    .addComponent(txtNyPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegDatum)
                    .addComponent(txtNyAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAndraUppgifter))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlatsForAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNyttDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNyPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNyPlatsActionPerformed
        // TODO add your handling code here:
        String gammalPlats = "Select Benamning from Plats Join Alien on Plats_ID=Plats where alien_id="+alienId;
        txtNyPlats.setText(gammalPlats);
    }//GEN-LAST:event_txtNyPlatsActionPerformed

    private void txtNyAnsvarigAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNyAnsvarigAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNyAnsvarigAgentActionPerformed

    private void txtNyttDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNyttDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNyttDatumActionPerformed

    private void txtNyTelNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNyTelNrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNyTelNrActionPerformed

    private void btnAndraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraUppgifterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndraUppgifterActionPerformed

    private void txtNyNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNyNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNyNamnActionPerformed

    private void txtNyRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNyRasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNyRasActionPerformed

    private void txtNyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNyIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNyIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentAndraInfoOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentAndraInfoOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentAndraInfoOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentAndraInfoOmAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AgentAndraInfoOmAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraUppgifter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAndraInfo;
    private javax.swing.JLabel lblAnsvarigAgent;
    private javax.swing.JLabel lblIDtForAlien;
    private javax.swing.JLabel lblNamnForAlien;
    private javax.swing.JLabel lblPlatsForAlien;
    private javax.swing.JLabel lblRas;
    private javax.swing.JLabel lblRegDatum;
    private javax.swing.JLabel lblTelNrForAlien;
    private javax.swing.JTextField txtNyAnsvarigAgent;
    private javax.swing.JTextField txtNyID;
    private javax.swing.JTextField txtNyNamn;
    private javax.swing.JTextField txtNyPlats;
    private javax.swing.JTextField txtNyRas;
    private javax.swing.JTextField txtNyTelNr;
    private javax.swing.JTextField txtNyttDatum;
    // End of variables declaration//GEN-END:variables
}
