/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realisering15;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Grupp15
 */
public class AlienFonster extends javax.swing.JFrame {

    private static InfDB databas;
    private String id;

    /**
     * Creates new form AlienFonster
     */
    public AlienFonster(InfDB databas, String id) {
        this.id = id;
        this.databas = databas;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlienFonsterText = new javax.swing.JLabel();
        btnVisaOCInfo = new javax.swing.JButton();
        btnLosenord = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAlienFonsterText.setText("Vad vill du göra?");

        btnVisaOCInfo.setText("Visa info om min områdeschef");
        btnVisaOCInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaOCInfoActionPerformed(evt);
            }
        });

        btnLosenord.setText("Ändra lösenord");
        btnLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLosenordActionPerformed(evt);
            }
        });

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblAlienFonsterText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnLosenord))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnVisaOCInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnLoggaUt)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblAlienFonsterText)
                .addGap(57, 57, 57)
                .addComponent(btnVisaOCInfo)
                .addGap(18, 18, 18)
                .addComponent(btnLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnLoggaUt)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Metod som visar upp information om områdeschefen för det område som alien befinner sig i
     */
    private void btnVisaOCInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaOCInfoActionPerformed

        try {
            String sqlSvarNamn = "SELECT agent.`Namn` FROM agent join omradeschef on agent.`Agent_ID` = omradeschef.`Agent_ID` join omrade on omradeschef.`Omrade` = omrade.`Omrades_ID` join alien on omrade.`Omrades_ID` = alien.`Plats` where alien.`Alien_ID` =" + id;
            String sqlSvarTelefon = "SELECT agent.`Telefon` FROM agent join omradeschef on agent.`Agent_ID` = omradeschef.`Agent_ID` join omrade on omradeschef.`Omrade` = omrade.`Omrades_ID` join alien on omrade.`Omrades_ID` = alien.`Plats` where alien.`Alien_ID` =" + id;
            String svarNamn = databas.fetchSingle(sqlSvarNamn);
            String svarTelefon = databas.fetchSingle(sqlSvarTelefon);
            
            JOptionPane.showMessageDialog(null, "Din områdeschef är: " +svarNamn+ ", telefonnummer " +svarTelefon);
        } catch (InfException ex) {
            Logger.getLogger(AlienFonster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVisaOCInfoActionPerformed

     /**
     * Metod som för användaren till ett nytt fönster för att ändra sitt lösenord
     */
    private void btnLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLosenordActionPerformed
        new AlienNyttLosenord(databas, id).setVisible(true);
    }//GEN-LAST:event_btnLosenordActionPerformed

     /**
     * Metod som loggar ut användaren och laddar om startfönstret (och rensar (genom att ej skicka med)
     * information om databasuppkoppling och användaren)
     */
    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        new Start(databas).setVisible(true);
        AlienFonster.this.dispose();
    }//GEN-LAST:event_btnLoggaUtActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnLosenord;
    private javax.swing.JButton btnVisaOCInfo;
    private javax.swing.JLabel lblAlienFonsterText;
    // End of variables declaration//GEN-END:variables
}
